repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.9
    hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
    - id: ruff-format

-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    - id: black
      language_version: python3
