name: Tests

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        uv venv
        uv pip install -e ".[test]"

    - name: Run tests
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        source .venv/bin/activate
        coverage run -m pytest sieves/tests/ -v
        coverage xml

#    - name: Upload coverage to Codecov
#      uses: codecov/codecov-action@v3
#      with:
#        files: coverage.xml
#        token: ${{ secrets.CODECOV_TOKEN }}
#        fail_ci_if_error: true
